### ISSUE TITLE
Breaking change - Data Structure

### ISSUE THREAD

**Issue by Norbz** [pluginpal/strapi-webtools#43]
### Summary

Hi
This is not really a feature request but more of a suggestion for longer term evolution. As it is more a reflexion on data structure, feel free to disagree with me, there's not a single truth on architecture.

⚠ This change wouldn't be backward compatible

Let me explain :)

### Why is it needed?

Right now, content types with url alias enabled have an injected url_path_id, which means your content-type is aware of the plugin managing it. This creates a few caveats : 
- When enabling the possibility to deactivate aliases for some content-type (beta 9), older content-type created before the update would require a manual cleanup on both files and database.
- Future similar evolution could create the same issue
- Removing the plugin leaves some unwanted data on every content-types that used to be managed by the plugin

### Suggested solution(s)

the table url_path should be storing the "remote" content-type id also, which would lead to the following structure :
- id
- url
- contenttype
- rid (remote ID, content-type entry UID)
- generated

This way, you have no field created on your content-type which leads to a lower footprint on user's data.
The only caveat I've came across is that when creating a new content-type entry, you need to store the URI in a temporary table because you need to get the "remote id" after the entry create (using the afterCreate hook) as you can't guess it before the entry is effectively created. It could lead to concurrency issues but Strapi isn't really good a concurrent edition anyway.

### Disclosure

I used to maintain the "custom-link" plugin available on strapi marketplace with a former coworker but I don't have enough time right now to work on it right now. I guess I should focus on trying to improve this one instead.

This is the approach we had when starting the project. I should try to implement it in here if you feel interested :)
Let me know what's your opinion on this

**Comment by Alexnortung** [comment]
I am pretty sure strapi cleans these columns up automatically with its automatic migrations. imo I agree on removing the `url_path_id` and adding a remote id column in the paths table, I did mention this in #33 as a potential solution.

And we can event make accessing the url path just as fast by creating a unique index of the content type and remote id columns.

The only problem as you mention, it is not backwards compatible and would require users to create a migration, but I think this is fine if this resolves bugs and improves performance.

**Comment by boazpoolman** [comment]
Backwards compatibility is not really we have to worry about at this point in time.
The plugin is released as an Alpha, so breaking changes are implied.

Though when we rethink the data structure I think we have to consider creating a "regular" Strapi relation between the content type and the url alias. That seems to me like the cleanest option, but I haven't figured out what it's implication might be.

@Alexnortung @Norbz How do you guys think about this?

**Comment by Alexnortung** [comment]
Current data structure:
It should be possible to create a regular relation, however I could not get it to work.

New data structure:
If you want to create a regular relation with a foreign key relation, then you need a column for each content type it could refer to, since a foreign key cannot refer to multiple tables.

**Comment by boazpoolman** [comment]
Yeah. So biggest downside would be a whole lot of relation tables. That doesn't seem so bad?

**Comment by Alexnortung** [comment]
I think you're right, however I just think it's gonna be alot more work and I also have some concerns about Strapi's content types:
How do you create new tables in strapi without creating new content types?
Is it even possible to dynamically create new content types in the `register()` hook?

So I think it is generally fine, but does this actually make it simpler? Does it provide any performance improvements?

On the other hand, Strapi provides a way to create custom indexes, so we could create a unique index on the two columns (remote id, content-type) to get performance as good as now.

Also other plugins such as [Navigation](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation) uses the technique @Norbz mentions (not that this makes it the correct choice)

**Comment by boazpoolman** [comment]
Thanks for all the input guys!

I'm trying to get to the core of the topic as @Norbz proposed.
Right now a `url_path_id` field is injected onto each content type.
@Norbz, you mentioned some downsides to that, let me try to respond to those:

The cleanup of the database will not be necessary when you disable URL alias. As Alex mentioned, the Strapi automatic migrations will clean them up for you. Also no files need to be cleaned up, because the schema change is done in the register function of the plugin. No physical change will be done to the schema.json file of your content type.

@Alexnortung to get back to you about the relational option. That IMO wouldn't mean we have to manually create tables in the register function. We would just change the `url_path_id` field to be a relational field by changing it's schema. That would then create all the linking tables for each content type for us.

I tried out a POC last week and writing up the field injection like this seemed to work:

```
_.set(attributes, 'url_alias', {
      writable: true,
      private: false,
      configurable: false,
      visible: false,
      default: null,
      type: "relation",
      relation: "oneToOne",
      target: "plugin::url-alias.url-path",
      unique: true,
    });
```

Going with said approach would still mean a field will be injected upon the content type of the user, which would mean a larger footprint, albeit an invisible field. And it would also still mean that the relation is one way. From the content type to the url alias, not the other way around. What that does in terms of performance I can't wrap my head around.

**Comment by Norbz** [comment]
@boazpoolman I thought strapi wouldn't clean the schema and the database but actually you are right, and my observation came from another (minor bug) : The "enable alias for the content-type" checkbox is deactivated by default, but the plugin consider the option to be true by default if not finding the following pluginOptions :

```
"url-alias": {
      "enabled": false
    }
```
    
 This lead me to believe it was deactivated when it was not, and thinking the reason it was activated was because of the remains of the url_path_id in the schema.
 
 Right now, you need to check the box, save, then uncheck it and save again so the plugin write the correct pluginOption.
 I should write another issue for this actually.
 
As for my suggestion, you don't need to add fields in the concerned content-type, but this means to match the relationship on logic level not on DB level. I understand that can be seen as a bad practice.

**Comment by boazpoolman** [comment]
I think I'm gonna try out both solutions.

1. Having an actual relation on the DB level.
2. Adding the remote id to the url alias table to match en entries that way. 

Let's see what works out.

**Comment by boazpoolman** [comment]
This feature has been released with the `beta` version of the plugin!
The URL aliases have been rewritten to be native relations.
If you're looking to migrate your existing URL aliases from `alpha` to `beta` please refer to the [migration guide](https://github.com/pluginpal/strapi-webtools/blob/master/MIGRATION.md).
